pgsql:
  dev:
    endpoint: '192.168.50.2'
    port: '31434'
    database_name: 'postgres'
    username: 'x81-test'
    password: 'DB5jK2G7g8XZupdf6zFnWLsbTN'
    schema: 'atp'

  stg:
    endpoint: '192.168.50.2'
    port: '31433'
    database_name: 'postgres'
    username: 'x81-stg'
    password: 'pT6umAFR57U9DBb2J8hejvSfZr'
    schema: 'atp'

  prod:
    endpoint: '192.168.50.2'
    port: '31432'
    database_name: 'postgres'
    username: 'x81k25'
    password: 'tQ9w5Tryf6cECsd73uLVpZJgaz'
    schema: 'atp'

