version: '3'

services:
  api:
    build:
      context: .
      dockerfile: app/Dockerfile.api
    image: reel-driver-image
    container_name: reel-driver-container
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    networks:
      - reel-driver-network

networks:
  reel-driver-network:
    driver: bridge