FROM python:3.12

WORKDIR /reel-driver

# Copy requirements and install dependencies
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# make directories to be used for file improts
# Copy application code
COPY ./app/ ./app
# Copy model artifacts
COPY ./model_artifacts ./model_artifacts

# Expose the port
EXPOSE 8000

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Run the application with reload enabled
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]